import os
import sys
import torch
import torch.optim as optim
import torch.nn as nn

# Ensure the project 'src' directory is in the system path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from models.vae import MusicVAE
from preprocessing.piano_roll import get_loader

def vae_loss(recon_x, x, mu, logvar, beta=0.1):
    # Total VAE objective: LV AE = Lrecon + beta * LKL
    recon_loss = nn.functional.binary_cross_entropy(recon_x, x, reduction='sum')
    # KL divergence
    kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return (recon_loss + beta * kl_loss) / x.size(0)

def train():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = MusicVAE().to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    
    # Path to the data generated by your MG parser
    data_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../data/processed/multi_genre_lmd.npy'))
    train_loader = get_loader(data_path, batch_size=64)
    
    epochs = 50
    print(f"Starting Task 2 Training on {device}...")
    
    for epoch in range(epochs):
        model.train()
        # KL weight beta annealing
        beta = min(0.1, epoch / 100.0) 
        
        total_loss = 0
        for batch in train_loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            recon, mu, logvar = model(batch)
            loss = vae_loss(recon, batch, mu, logvar, beta=beta)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        
        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f"Epoch {epoch+1}/{epochs} | Avg Loss: {total_loss/len(train_loader):.4f} | Beta: {beta:.3f}")

    # Save the trained multi-genre weights
    save_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../models/vae_weights.pt'))
    torch.save(model.state_dict(), save_path)
    print(f"VAE Training Complete. Weights saved to {save_path}")

if __name__ == "__main__":
    train()