import torch
import torch.optim as optim
import torch.nn as nn
import os
from models.vae import MusicVAE
from preprocessing.piano_roll import get_loader

def vae_loss(recon_x, x, mu, logvar, beta=0.1):
    # L_vae = L_recon + beta * L_KL
    recon_loss = nn.functional.binary_cross_entropy(recon_x, x, reduction='sum')
    kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return (recon_loss + beta * kl_loss) / x.size(0)

def train():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = MusicVAE().to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    
    # Using the multi-genre .npy file generated by the new parser
    train_loader = get_loader('data/processed/multi_genre_lmd.npy', batch_size=64)
    
    epochs = 50
    for epoch in range(epochs):
        model.train()
        # β-annealing to prevent posterior collapse
        beta = min(0.1, epoch / 100.0) 
        
        for batch in train_loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            recon, mu, logvar = model(batch)
            loss = vae_loss(recon, batch, mu, logvar, beta=beta)
            loss.backward()
            optimizer.step()
        
        if (epoch + 1) % 5 == 0:
            print(f"Epoch {epoch+1}/{epochs} | Loss: {loss.item():.4f}")

    os.makedirs('src/models', exist_ok=True)
    torch.save(model.state_dict(), 'src/models/vae_weights.pt')
    print("VAE Training Complete.")

if __name__ == "__main__":
    train()